### PR TITLE
Create logo.svg

### PR DESCRIPTION
**Pull request by benjaminbellamy**

### CODE REVIEW

**Comment by ByteHamster** [comment]
Thanks for working on this. I think that it is important to have an svg version that can be opened with open-source programs.

The converted svg looks a bit different to the original version, though. It is missing some shadows and looks less "alive". Would you be up for modifying the file, so that it looks the same as the original one?

yours / original:
image

**Comment by benjaminbellamy** [comment]
I updated it:
https://github.com/benjaminbellamy/Branding/blob/patch-1/Logo/logo.svg

**Comment by ByteHamster** [comment]
Thanks! Looks a lot more similar now. It is still missing the background gradient and some slight shadows of the foreground elements, though. I know this is pretty annoying to do but we went through countless iterations with the designer, so the svg version should be as close to the original as possible. Would be great if you could have another look :)

**Comment by benjaminbellamy** [comment]
Oooooh…
I had not seen there was a gradient!
I just added it: https://github.com/benjaminbellamy/Branding/blob/patch-1/Logo/logo.svg
Regarding the slight shadows of the foreground elements, I don't see them, can you be more specific?

**Comment by ByteHamster** [comment]
> I just added it

Thanks!

> Regarding the slight shadows of the foreground elements, I don't see them, can you be more specific?

Just did a few screenshots in Figma where the icon was designed, see gif below

**Comment by ByteHamster** [comment]
Hi @benjaminbellamy are you interested in finishing the conversion? Would be great to have the logo in a format that is more open-source friendly than a figma file :)

**Comment by benjaminbellamy** [comment]
I would love to help but I am not able to draw it from a gif without detailed specs. :-/
Can you provide exact color / opacity, vertical blur / horizontal blur, X offset / Y offset?

**Comment by benjaminbellamy** [comment]
Why don't you export to SVG?
https://help.figma.com/hc/en-us/articles/360040028114-Guide-to-exports-in-Figma#h_41b394ed-f969-4840-9e6e-c7c2790d5bc5

**Comment by ByteHamster** [comment]
> Why don't you export to SVG?

The files exported by Figma are corrupted in Inkscape (see image below). I think it would be good to have an official svg file that can be read correctly in open-source tools, not just in proprietary software.



> Can you provide exact color / opacity, vertical blur / horizontal blur, X offset / Y offset?

To be honest, I don't know. The figma source file as well as a broken svg export (see image above) can be found here: https://github.com/AntennaPod/Branding/tree/master/Source%20Files

**Comment by keunes** [comment]
> I would love to help but I am not able to draw it from a gif without detailed specs. :-/

I'm checking the Figma file now to see if I can identify them

**Comment by keunes** [comment]
@benjaminbellamy
This seems to be the specs for the shadow in question of the antenna (legs & circle on top):
image

The waves have the same, but with **15 %**.

Hope this helps to get a proper svg (and I'm sorry I let the designer work in figma and not provide a proper svg file, even though it was in our requirements - your help here is much appreciated!!)

**Comment by benjaminbellamy** [comment]
I tried that: https://github.com/benjaminbellamy/Branding/blob/patch-1/Logo/logo.svg

**Comment by ByteHamster** [comment]
Hmm, it still somehow looks different, doesn't it? I think the shadow looks more prominent in the svg version than in the png version.

Sorry for being so picky :/

**Comment by benjaminbellamy** [comment]
I applied the values provided by @keunes …
Here is another shot: https://github.com/benjaminbellamy/Branding/blob/patch-1/Logo/logo.svg

**Comment by ByteHamster** [comment]
> I applied the values provided by @keunes …

Maybe the size is different, so the numbers do not end up the same.

It's clearly getting there and I feel sorry for complaining so much. I hope that you are not annoyed by my perfectionism :)

Have a look at the gif below - I think it still needs a few tweaks. The hard shadow seems to have a gradient in the version of the designer and is a bit darker in the bottom. The soft shadow seems to be a bit more subtle in the version of the designer.

**Comment by keunes** [comment]
In the figma file I saw there was a layer on top of the whole icon that gave a white wash, which I think is missing from the SVG version.
It seems the 'hard' shadow is missing from the antenna. Edit: it seems it was there in your original version. Did you perhaps change its settings (apply the blur) rather than add an extra shadow layer?

The 'soft' shadow layer is much harder in the SVG than in the figma version. Is it possible that the shadow blur is identified differently between programmes? E.g. in figma it's 3 % and in something else it's 3 px or so, or 3% to another reference point?

**Comment by ByteHamster** [comment]
> It seems the 'hard' shadow is missing from the antenna

It is there but it somehow has the same color as the soft shadow

> In the figma file I saw there was a layer on top of the whole icon that gave a white wash, which I think is missing from the SVG version.

I think we can omit that. The background looks pretty much the same without it. (on the splash screen, for example, I also removed it because it makes showing the image harder). When tweaking the shadows a little bit, it should look the same :)

**Comment by elioqoshi** [comment]
@keunes I would not suggest perfectly recreating the logo as it used to be. There are technically many inaccuracies which should rather be fixed than recreated. The hard shadows don't look consistent if they are directed to the bottom, as the shapes are round and create an inconsistent shadow stroke which is thinner or thicker at given points. The A is also not well designed on the bottom of its arch. 

I would suggest redesign the logo to be well eligible on small sizes and various use cases. That means it won't look exactly like it did before and that would be a slight improvement. A quick draft of what would work best nowadays: 
image

Recreating it exactly like it was is futile I'd say. You have the opportunity to improve things now and don't need to stick to exactly what you had :)

**Comment by ByteHamster** [comment]
Thanks for working on it @elioqoshi!

I'm no design expert but to me, personally, your suggestion looks more "flat" and not as "vivid" as the original design. Setting it as an icon and looking at it on my phone, your version also seems to have less contrast between waves and background, making them slightly harder to see. Even though the change is barely noticeable when looking at it with the small icon size on my phone, the original somehow looks a bit more "catchy" to me, personally.



> The A is also not well designed on the bottom of its arch.

What do you mean with this? I'm not sure if that is just my imagination but it feels like the bar of the old icon's "A" extends the wave circle, while your design makes it more straight. Is this what you mean?

> Recreating it exactly like it was is futile I'd say.

Okay, maybe we don't have to recreate it exactly. I still think that there could be some discussion about what to change/simplify, though :see_no_evil: (sorry for being so picky)

**Comment by keunes** [comment]
Hi @elioqoshi,

Thanks a lot for offering your help and guidance - much appreciated! :)

> Recreating it exactly like it was is futile I'd say. You have the opportunity to improve things now and don't need to stick to exactly what you had :)

I fully agree. I like what you proposed, but also understand where ByteHamster is coming from, concerning the contrast - it 'pops' a bit less. Do you think we could improve on this front a bit, e.g. with a slightly stronger shadow, and maybe a touch darker bottom colour (or even a touch more direction purple)?

> The A is also not well designed on the bottom of its arch.

Do you mean that it's not actually round/equally curved throughout? Hadn't noticed before :) That seems to be an issue with the SVG version - in Figma-based version it doesn't look like that. Would be great if that could be addressed indeed.

> I still think that there could be some discussion about what to change/simplify, though

I checked with ByteHamster and his main concern was with the point I mentioned again above. So, just to be clear, it's not that we want to have a big discussion first :)

Thanks again for your help!

**Comment by ueen** [comment]
@elioqoshi I think your version looks better than the original, maybe make the shadows opacity a little higher (=>darker) to elevate contrast, otherwise I'd say it looks supreme, is it a svg?

**Comment by elioqoshi** [comment]
@keunes I get what you mean. I will propose a few options so we can go through them. Do we have a standard color palette guideline to use? Also, could you provide the Figma file as the SVG is faulty?

**Comment by keunes** [comment]
Awesome, thank you @elioqoshi. The icon/logo was created first, and from that I extracted two main colours (though I tweaked them a bit because of the contrast), adding a third to get something like a colour palette: https://design.penpot.app/#/view/a5ee86a0-bae2-11eb-8670-bcf80c3b5feb?page-id=a5ee86a1-bae2-11eb-8670-bcf80c3b5feb&index=0&section=interactions&share-id=e4226240-1fd0-11ec-9b4d-b2702b3a67d1

But I would be more than happy to adjust the stylesheet again according to any agreed changes :) (if you have any other comments or thoughts, please feel free share).

Please find here the Figma file (I believe this is the version we received, without any edits): [AntennaPod.zip](https://github.com/AntennaPod/Branding/files/7834027/AntennaPod.zip)

**Comment by elioqoshi** [comment]
The thing is that shadows are not natively supported in SVG which can result in unexpected results. But here is another version I tried:  
image
[AntennaPod.svg.zip](https://github.com/AntennaPod/Branding/files/7835703/AntennaPod.svg.zip)

**Comment by ByteHamster** [comment]
Thanks, the new version feels like it has similar depth as the original icon. I think I like it. I'm still a bit worried about changing the icon again, after just about 1 year. Having to update it everywhere will probably open the way for inconsistencies. To me, it feels a bit like we are changing the icon because of the limitations of the SVG format, not because we actually want to change the icon. Anyway, You are a designer and I'm not. If you are really convinced that changing the icon is a good idea, I'm in :+1:



By the way, the svg file you attached looks different on my PC when viewing it using Inkscape:

**Comment by keunes** [comment]
Sorry for the late reaction. Thanks @elioqoshi for that updated version and @ByteHamster for your comment.

> Having to update it everywhere will probably open the way for inconsistencies.

That's always a risk. But as we're not that big of a brand the logo will be in fewer places outside our control, with not such a high risk on inconsistencies. Plus there's no physical stock we need to get rid of. And as the main elements stay the same, simple extractions like in the [podcast font](https://podcastfont.com/) probably aren't affected :)

> here is another version I tried

Like it! If my eyes don't betray me, the shadows are a bit more intense and the bottom background colour a bit darker. I like the latter, feel the shadows are a notch too much (or maybe they just seem more intense because of the backgr colour change?).

If you don't mind, I would be curious for one with that little bit less shadow. And if that feels right, I'd be happy go with it :)

**Comment by keunes** [comment]
@ByteHamster do you think the updated logo could still be incorporated in the 2.5 release?

Edit: ah, I see you released the first beta already 🙂👍 So I guess you'd prefer not (?)

**Comment by elioqoshi** [comment]
@keunes Sorry I am not sure if I can be useful here with tweaking shadows since you have a specific vision of how it shouuld be. It would be probably best if I send you the Figma source file so you can review it yourself eventually?

**Comment by keunes** [comment]
Hi @elioqoshi,
Many thanks again for the follow-up. After your comment I reflected a bit on my thoughts about the shadow, why it might have felt a bit too intense. Comparing the two versions you made, I think it's because there now also is a shadow a the top/outside of the waves/antenna. I like that in the first version it doesn't (top & bottom aren't 'symmetric'):

comparison

I guess what I was wondering/asking if the shadows of the waves could be a bit more 'transparent' (less dark) and/or placed/done more in the way as in your first version (less at the top/outside of the waves). Hope that what I'm saying makes sense :P

I'd be happy to fiddle with the figma file, though I'm not sure I'd trust myself as I might well mess up the file or create something that you don't think is good ^^

**Comment by ByteHamster** [comment]
We have recently worked together with @ryangorley from Freehive to get to an updated icon design. Ryan also made an SVG version of the icon, which you can find here: https://github.com/AntennaPod/Branding/blob/master/Logo/logo-icon.svg

Thank you everyone for participating in this PR!

**Pull request closed without merging**
