### PR TITLE
Android auto screenshots

### PR DESCRIPTION
**Pull request by tonytamsf**
Android auto screenshots

Let me know how you wanted me to generate the screenshots

@keunes , @ByteHamster

### CODE REVIEW

**Comment by keunes** [comment]
Thank @tonytamsf for this! Having the screenshots (even without a 'frame') is already nice. We can manually include this in a 'devices' overview.

How did you create the screenshots?
And I feel that the images are a bit stretched vertically - is that possible?

**Comment by tonytamsf** [comment]
Glad they will help.

I created these using the Android Autos Desktop Head Unit emulator https://developer.android.com/training/cars/testing

I don't think they are stretched, that is the aspect ratio of the emulator.  I can double check.

**Comment by ByteHamster** [comment]
Thanks for creating the screenshots! I think the screenshots could be easier to integrate with the script if they did not contain the shadow and transparent background.

Do we need multiple screenshots? Looking at https://github.com/AntennaPod/AntennaPod/issues/4044, I think we should create one image with a TV (Chromecast), a tablet, a phone, a watch and a car.

**Comment by keunes** [comment]
> Do we need multiple screenshots?

Not for the overview image, but in other situations it might be good to have it. (I'm thinking an automotive magazine  that writes about audio options).

**Comment by tonytamsf** [comment]
Hmm, I will looks at the transparency, maybe I can show day time mode

**Comment by tonytamsf** [comment]
Are these any better?

auto-01
auto-02
auto-03
auto-04
auto-05

**Comment by keunes** [comment]
They're not stretched :) And I think no shadow either? (Checkin on mobile)

What did you do differently?

**Comment by tonytamsf** [comment]
Instead of doing a screenshot on my monitor, I used the `screenshot` command in the HUD.  I am not very good at telling the stretched or transparency.  If these are good, I will change my PR

**Comment by ByteHamster** [comment]
Oh, sorry. I forgot about this PR. Do you still have the screenshots? (if not, we can just take the ones uploaded here on GitHub). Not sure how soon we will actually use them for the overview screenshots but it would be sad to throw away the work you did.

**Comment by tonytamsf** [comment]
> Oh, sorry. I forgot about this PR. Do you still have the screenshots? (if not, we can just take the ones uploaded here on GitHub). Not sure how soon we will actually use them for the overview screenshots but it would be sad to throw away the work you did.


@ByteHamster  I could take more screenshots if you wanted or the ones I uploaded would be fine.  I'll move them into the right files. Did we want screenshots of light mode?

**Comment by ByteHamster** [comment]
I think just dark mode is fine and the ones you created look great :)

**Comment by tonytamsf** [comment]
> I think just dark mode is fine and the ones you created look great :)

Okay, I've pushed the files in.

**Comment by ByteHamster** [comment]
Thanks!

**Pull request merged**
